name: Release

on:
  push:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-pull-request:
    name: Version Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: 20
      - name: Build
        uses: ./.github/actions/build
      - name: Create Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "Version Packages"
          commit: "version packages"

  # publish:
  #   name: Publish
  #   needs: version-pull-request
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #     id-token: write
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Install dependencies
  #       uses: ./.github/actions/install-dependencies
  #       with:
  #         node_version: 20
  #     - name: Publish to NPM
  #       uses: changesets/action@v1
  #       with:
  #         createGithubReleases: true
  #         publish: "npm run changeset:publish"
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
