name: Release

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    # Only run this job if the pull request was pull request from changesets
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event.pull_request.merged == true &&
      github.event.pull_request.title == 'Version Packages')
    name: Release on GitHub and publish to npm
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: 20
      - name: Build
        uses: ./.github/actions/build
      - name: Create Release and Publish
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        with:
          createGithubReleases: true
          publish: "npm run changeset:publish"
